from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import HttpResponse

urlpatterns = [
    path('',home),
    path('login',login),
    path('stateselection',stateselection),
    path('stateform', stateform),
    path('rajasthanform',rajasthan_data),
    path('punjabform',punjab_data),
    path('rajasthan_recipt/<str:id>',rajasthan_pdf),
    path('rajasthan_scan/<str:id>',rajasthan_scan),
    path('punjab_recipt/<str:id>',punjab_pdf),
    path('punjab_scan/<str:id>',punjab_scan),
    path('haryanaform',haryana_data),
    path('haryana_recipt/<str:id>',haryana_pdf),
    path('bihar_form',bihar_data),
    path('bihar_recipt/<str:id>',bihar_recipt),
    path('gujrat_form',gujrat_data),
    path('gujrat_recipt/<str:id>',gujrat_pdf),
    path('himachal_form',himachal_data),
    path('himachal_recipt/<str:id>',himachal_recipt),
    path('karnatka_form',karnatka_data),
    path('karnataka_recipt/<str:id>',karnataka_recipt),
    path('jharkhand_form',jharkhand_data),
    path('jharkhand_recipt/<str:id>',jharkhand_recipt),
    path('madhyapradesh_form',madhyapradesh_data),
    path('madhyapradesh_recipt/<str:id>',madhyapradesh_recipt),
    path('maharashtra_form',maharashtra_data),
    path('maharashtra_recipt/<str:id>',maharashtra_recipt),
    path('tamilnadu_form',tamilnadu_data),
    path('tamilnadu_recipt/<str:id>',tamilnadiu_recipt),
    path('tamilnadiu_recipt/<str:id>',tamilnadiu_recipt),
    path('uttarpradesh_form',uttarpradesh_data),
    path('uttarpradesh_recipt/<str:id>',uttarpradesh_recipt),
    path('uttrakhand_form',uttrakhand_data),
    path('uttrakhand_recipt/<str:id>',uttrakhand_recipt),
    path('uttrakhand_scan/<str:id>',uttrakhand_scan),
    path('tripura_form',tripura_data),
    path('tripura_recipt/<int:id>',tripura_recipt),
    path('gujrat_odc_form',gujrat_odc_data),
    path('gujrat_odc_recipt/<str:id>',gujrat_odc_recipt),
    path('gujrat_odc_scan/<str:id>',gujrat_odc_scan),
    path('tax_history/<str:statename>',all_recipt_history),
        path('logout',logout_admin),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
