# Generated by Django 5.0.1 on 2024-07-12 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vhaanmain', '0049_remove_stateassign_admin_custom_admin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='default', max_length=80)),
                ('admin_password', models.CharField(default='default', max_length=80)),
                ('auth_token', models.CharField(default=uuid.uuid4, editable=False, max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='stateAssign_admin_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.admin_list')),
                ('state_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.statelists')),
            ],
        ),
    ]
