# Generated by Django 5.0.1 on 2024-03-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
