# Generated by Django 5.0.1 on 2024-03-06 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0004_rename_user_id_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelists',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default=uuid.uuid4, max_length=2000),
        ),
    ]
