# Generated by Django 5.0.1 on 2024-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0005_alter_statelists_id_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateassigned',
            name='state_id',
        ),
        migrations.AddField(
            model_name='stateassigned',
            name='state_id',
            field=models.ManyToManyField(to='vhaanmain.statelists'),
        ),
    ]
