# Generated by Django 5.0.1 on 2024-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0006_remove_stateassigned_state_id_stateassigned_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateassigned',
            name='state_id',
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stateassigned',
            name='state_id',
            field=models.IntegerField(null=True),
        ),
    ]
