# Generated by Django 5.0.1 on 2024-03-06 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0007_remove_stateassigned_state_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.statelists'),
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.user'),
        ),
        migrations.AlterField(
            model_name='statelists',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
