# Generated by Django 5.0.1 on 2024-03-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0009_rename_state_id_stateassigned_state_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=40)),
                ('owner_name', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=60)),
                ('vehicle_class', models.CharField(max_length=60)),
                ('chassis_no', models.CharField(max_length=80)),
            ],
        ),
    ]
