# Generated by Django 5.0.1 on 2024-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0010_vehicle_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_rajasthan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('vehicleno', models.CharField(max_length=120)),
                ('chassisno', models.CharField(max_length=120)),
                ('ownername', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120)),
                ('from_state', models.CharField(max_length=120)),
                ('VehicleType', models.CharField(max_length=120)),
                ('VehicleClass', models.CharField(max_length=120)),
                ('seating_c', models.CharField(max_length=120)),
                ('txt_sleeper_cap', models.CharField(max_length=120)),
                ('PermitType', models.CharField(max_length=120)),
                ('border_entry', models.CharField(max_length=120)),
                ('checkpost_name', models.CharField(max_length=120)),
                ('TaxMode', models.CharField(max_length=120)),
                ('txt_no_of_weeks', models.CharField(max_length=120)),
                ('tax_from', models.CharField(max_length=120)),
                ('tax_upto', models.CharField(max_length=120)),
                ('total_tax_amount', models.CharField(max_length=120)),
                ('civik_amount', models.CharField(max_length=120)),
                ('service_amount', models.CharField(max_length=120)),
                ('Weight', models.CharField(max_length=120)),
                ('sleeper_Cap_Weight', models.CharField(max_length=120)),
                ('counter_fee', models.CharField(max_length=120)),
                ('create_date', models.CharField(max_length=120)),
                ('recipt_no', models.CharField(max_length=120)),
            ],
        ),
    ]
