# Generated by Django 5.0.1 on 2024-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0011_add_rajasthan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_rajasthan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
