# Generated by Django 5.0.1 on 2024-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0012_alter_add_rajasthan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_rajasthan',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='media/qr/rajasthan/'),
        ),
    ]
