# Generated by Django 5.0.1 on 2024-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0014_remove_add_rajasthan_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_punjab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=80)),
                ('vehicleno', models.CharField(max_length=80)),
                ('chassisno', models.CharField(max_length=80)),
                ('ownername', models.CharField(max_length=80)),
                ('mobile', models.CharField(max_length=80)),
                ('from_state', models.CharField(max_length=80)),
                ('VehicleType', models.CharField(max_length=80)),
                ('VehicleClass', models.CharField(max_length=80)),
                ('SeatingOrWeight', models.CharField(max_length=80)),
                ('seatingOrLaden', models.CharField(max_length=80)),
                ('unldweightOrSleeper', models.CharField(max_length=80)),
                ('ServiceType', models.CharField(max_length=80)),
                ('TaxMode', models.CharField(max_length=80)),
                ('border_entry', models.CharField(max_length=80)),
                ('districtname', models.CharField(max_length=80)),
                ('entrydate', models.CharField(max_length=80)),
                ('outdate', models.CharField(max_length=80)),
                ('total_amount', models.CharField(max_length=80)),
                ('usercharge', models.CharField(max_length=80)),
                ('infracess', models.CharField(max_length=80)),
                ('create_date', models.CharField(max_length=80)),
                ('recipt_no', models.CharField(max_length=80)),
            ],
        ),
    ]
