# Generated by Django 5.0.1 on 2024-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0015_add_punjab'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_haryana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_username', models.CharField(max_length=80)),
                ('vehicleno', models.CharField(max_length=80)),
                ('chassisno', models.CharField(max_length=80)),
                ('ownername', models.CharField(max_length=80)),
                ('mobile', models.CharField(max_length=80)),
                ('from_state', models.CharField(max_length=80)),
                ('VehicleType', models.CharField(max_length=80)),
                ('VehicleClass', models.CharField(max_length=80)),
                ('seating_c', models.CharField(max_length=80)),
                ('ServiceType', models.CharField(max_length=80)),
                ('distance', models.CharField(max_length=80)),
                ('TaxMode', models.CharField(max_length=80)),
                ('border_entry', models.CharField(max_length=80)),
                ('entrydate', models.CharField(max_length=80)),
                ('outdate', models.CharField(max_length=80)),
                ('total_amount', models.CharField(max_length=80)),
                ('Weight', models.CharField(max_length=80)),
            ],
        ),
    ]
