# Generated by Django 5.0.1 on 2024-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0016_add_haryana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_haryana',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
