# Generated by Django 5.0.1 on 2024-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0017_alter_add_haryana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_haryana',
            name='created_username',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
