# Generated by Django 5.0.1 on 2024-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0018_alter_add_haryana_created_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_haryana',
            name='ServiceType',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='TaxMode',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='VehicleClass',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='VehicleType',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='Weight',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='border_entry',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='chassisno',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='distance',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='entrydate',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='from_state',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='mobile',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='outdate',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='ownername',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='seating_c',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='total_amount',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='add_haryana',
            name='vehicleno',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
