# Generated by Django 5.0.1 on 2024-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0022_add_jharkhand_add_karnataka_add_madhyapradesh_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicle_data',
        ),
        migrations.AddField(
            model_name='add_punjab',
            name='mv_tax',
            field=models.CharField(default=80, max_length=80),
        ),
    ]
