# Generated by Django 5.0.1 on 2024-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0023_delete_vehicle_data_add_punjab_mv_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=80)),
                ('admin_password', models.CharField(max_length=80)),
                ('auth_token', models.CharField(max_length=280)),
            ],
        ),
        migrations.AddField(
            model_name='add_bihar',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_gujrat',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_haryana',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_himachal',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_jharkhand',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_karnataka',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_madhyapradesh',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_maharashtra',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_punjab',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_rajasthan',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_tamilnadu',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_uttarpradesh',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_uttrakhand',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
    ]
