# Generated by Django 5.0.3 on 2024-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0023_delete_vehicle_data_add_punjab_mv_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_bihar',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_gujrat',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_haryana',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_himachal',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_jharkhand',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_karnataka',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_madhyapradesh',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_maharashtra',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_punjab',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_rajasthan',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_tamilnadu',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_uttarpradesh',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
        migrations.AddField(
            model_name='add_uttrakhand',
            name='total_amt_text',
            field=models.CharField(default='nothing', max_length=180),
        ),
    ]
