# Generated by Django 5.0.1 on 2024-03-18 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0024_admin_list_add_bihar_total_amt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_list',
            name='permanent_id',
            field=models.CharField(default=uuid.uuid4, max_length=280),
        ),
    ]
