# Generated by Django 5.0.1 on 2024-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0025_admin_list_permanent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
