# Generated by Django 5.0.1 on 2024-03-18 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0026_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=280),
        ),
    ]
