# Generated by Django 5.0.1 on 2024-03-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0027_user_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_list',
            name='permanent_id',
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.user_custom'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
