# Generated by Django 5.0.1 on 2024-03-18 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0028_user_custom_remove_admin_list_permanent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='created_by',
            field=models.CharField(default='null', max_length=280),
        ),
        migrations.AddField(
            model_name='user_custom',
            name='user_uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=280),
        ),
    ]
