# Generated by Django 5.0.1 on 2024-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0029_user_custom_created_by_user_custom_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_list',
            name='auth_token',
            field=models.UUIDField(),
        ),
    ]
