# Generated by Django 5.0.1 on 2024-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0030_alter_admin_list_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_list',
            name='auth_token',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='user_custom',
            name='user_uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
