# Generated by Django 5.0.1 on 2024-03-18 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0031_alter_admin_list_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_list',
            name='auth_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=280),
        ),
    ]
