# Generated by Django 5.0.1 on 2024-03-18 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0032_alter_admin_list_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='user_uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=280),
        ),
    ]
