# Generated by Django 5.0.3 on 2024-03-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0024_add_bihar_total_amt_text_add_gujrat_total_amt_text_and_more'),
        ('vhaanmain', '0033_alter_user_custom_user_uuid'),
    ]

    operations = [
    ]
