# Generated by Django 5.0.3 on 2024-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0034_merge_20240320_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_gujrat_odc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_user', models.CharField(max_length=280)),
                ('vehicle', models.CharField(max_length=280)),
                ('chassis', models.CharField(max_length=280)),
                ('owner_type', models.CharField(max_length=280)),
                ('owner_name', models.CharField(max_length=280)),
                ('mobileno', models.CharField(max_length=280)),
                ('vehicle_type', models.CharField(max_length=280)),
                ('vehicle_class', models.CharField(max_length=280)),
                ('gross_wt', models.CharField(max_length=280)),
                ('unladen_wt', models.CharField(max_length=280)),
                ('body_type', models.CharField(max_length=280)),
                ('goods_nature_input', models.CharField(max_length=280)),
                ('over_dimension_input', models.CharField(max_length=280)),
                ('permit_type_input', models.CharField(max_length=280)),
                ('txt_permit_no', models.CharField(max_length=280)),
                ('road_tax_val', models.CharField(max_length=280)),
                ('state_from', models.CharField(max_length=280)),
                ('district_input', models.CharField(max_length=280)),
                ('state_to', models.CharField(max_length=280)),
                ('to_district_input', models.CharField(max_length=280)),
                ('insurance_val', models.CharField(max_length=280)),
                ('fitness_val', models.CharField(max_length=280)),
                ('pucc_val', models.CharField(max_length=280)),
                ('permit_val', models.CharField(max_length=280)),
                ('lr_no', models.CharField(max_length=280)),
                ('lr_date', models.CharField(max_length=280)),
                ('goodd_description_input', models.CharField(max_length=280)),
                ('total_tax_amount', models.CharField(max_length=280)),
                ('payment_date', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='add_tripura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipt_no', models.CharField(max_length=280)),
                ('created_user', models.CharField(max_length=280)),
                ('vehicle', models.CharField(max_length=280)),
                ('chassis', models.CharField(max_length=280)),
                ('owner', models.CharField(max_length=280)),
                ('mobileno', models.CharField(max_length=280)),
                ('statename', models.CharField(max_length=280)),
                ('vehicleType', models.CharField(max_length=280)),
                ('vehicleClass', models.CharField(max_length=280)),
                ('grossWeight', models.CharField(max_length=280)),
                ('district', models.CharField(max_length=280)),
                ('barrier', models.CharField(max_length=280)),
                ('payment_mode', models.CharField(max_length=280)),
                ('cal_tax_from_input', models.CharField(max_length=280)),
                ('cal_tax_to_input', models.CharField(max_length=280)),
                ('mv_tax', models.CharField(max_length=280)),
                ('Service_charge', models.CharField(max_length=280)),
                ('total_tax_amount', models.CharField(max_length=280)),
                ('text_amt', models.CharField(max_length=280)),
                ('payment_date', models.CharField(max_length=280)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_gujrat',
            name='total_amt_text',
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='total_tax_amount',
            field=models.CharField(default='nothing', max_length=180),
        ),
    ]
