# Generated by Django 5.0.3 on 2024-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0035_add_gujrat_odc_add_tripura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gujrat_odc',
            name='lr_date',
        ),
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='conHeight_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='conLength_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='conWidth_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='remarks',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='barrier',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='chassis_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='client_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='from_district',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='loading_capacity',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='owner_mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='owner_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='payment_mode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='permit_type',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='sitting_capacity',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='sleeper_capacity',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='tax_mode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='tax_total',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='vehicle',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='vehicle_class',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_bihar',
            name='vehicle_type',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='makerstatus',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='ownertype',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='permit_ia',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='permit_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='permit_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='ptype',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='body_type',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='chassis',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='created_user',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='district_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='fitness_val',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='goodd_description_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='goods_nature_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='gross_wt',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='insurance_val',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='lr_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='mobileno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='over_dimension_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='owner_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='owner_type',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='payment_date',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='permit_type_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='permit_val',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='pucc_val',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='road_tax_val',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='state_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='state_to',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='to_district_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='txt_permit_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='unladen_wt',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='vehicle',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='vehicle_class',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_gujrat_odc',
            name='vehicle_type',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='service_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='txt_no_of_weeks',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_himachal',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='PermitType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='checkpost',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='txt_no_of_weeks',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_jharkhand',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='PermitType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='fitdate',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='infra_cess',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='ins_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='permit_endoresment_variation',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='permit_fee',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='permit_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='service_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='tax_validity',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='txt_floor_area',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='txt_no_of_weeks',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_karnataka',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='genby',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='gramin',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='tax_consessioner',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='tax_ips',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='tax_mode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_madhyapradesh',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='checkpost',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='create_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='districtname',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='service_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_maharashtra',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='SeatingOrWeight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='create_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='districtname',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='entrydate',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='infracess',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='outdate',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='recipt_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='seatingOrLaden',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='total_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='unldweightOrSleeper',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='user_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='usercharge',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_punjab',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='Extra_seat_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='Greentax',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='PermitType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='cal_tax_from_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='cal_tax_to_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='checkpost_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='create_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='districtname',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='fitness_valid_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='ins_validity_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='issuing_authority',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='mv_tax',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='permit_authorization_vali',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='permit_upto_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='permitfree',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='pucc_validity_input',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='recipt_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='regn_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='serviceusercharge',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='txt_permit_auth_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='txt_permit_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='txt_seat_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tamilnadu',
            name='welfaretax',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='Service_charge',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='barrier',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='cal_tax_from_input',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='cal_tax_to_input',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='chassis',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='created_user',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='district',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='grossWeight',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='mobileno',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='mv_tax',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='owner',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='payment_date',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='payment_mode',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='recipt_no',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='statename',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='text_amt',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='vehicle',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='vehicleClass',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_tripura',
            name='vehicleType',
            field=models.CharField(default='default', max_length=280),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='PermitType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='permit_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='permit_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttarpradesh',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='Pay_Tax',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='PermitType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='ServiceType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='TaxMode',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='VehicleClass',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='VehicleType',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='border_entry',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='chassisno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='civik_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='created_username',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='districtname',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='fitdate',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='from_state',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='mobile',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='ownername',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='payment_date',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='permit_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='permit_no',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='permit_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='seating_c',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='service_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='tax_from',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='tax_upto',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='total_tax_amount',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='txt_no_of_weeks',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='txt_sleeper_cap',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='add_uttrakhand',
            name='vehicleno',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='admin_list',
            name='admin_name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='admin_list',
            name='admin_password',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
