# Generated by Django 5.0.3 on 2024-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0036_remove_add_gujrat_odc_lr_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='amount_text',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='add_gujrat_odc',
            name='lr_date',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
