# Generated by Django 5.0.1 on 2024-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0037_add_gujrat_odc_amount_text_add_gujrat_odc_lr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_uttarpradesh',
            name='recipt_no',
            field=models.CharField(default='default', max_length=70),
        ),
    ]
