# Generated by Django 5.0.1 on 2024-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0040_user_custom_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_bihar',
            name='recipt_no',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
