# Generated by Django 5.0.1 on 2024-07-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0041_add_bihar_recipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gujrat',
            name='recipt_no',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
