# Generated by Django 5.0.1 on 2024-07-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0042_add_gujrat_recipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_himachal',
            name='recipt_no',
            field=models.CharField(default='default', max_length=70),
        ),
        migrations.AlterField(
            model_name='statelists',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
