# Generated by Django 5.0.1 on 2024-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0043_add_himachal_recipt_no_alter_statelists_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
