# Generated by Django 5.0.1 on 2024-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0044_alter_user_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateassigned',
            name='state_name',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='user_name',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
