# Generated by Django 5.0.1 on 2024-07-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0045_alter_stateassigned_state_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateassigned',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.statelists'),
        ),
        migrations.AlterField(
            model_name='stateassigned',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vhaanmain.user_custom'),
        ),
    ]
