# Generated by Django 5.0.1 on 2024-07-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0047_stateassign_admin_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateassign_admin_custom',
            old_name='user_name',
            new_name='admin_name',
        ),
    ]
