# Generated by Django 5.0.1 on 2024-07-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0049_remove_stateassign_admin_custom_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelists',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
