# Generated by Django 5.0.1 on 2024-07-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0050_alter_statelists_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_uttarpradesh',
            name='Weight',
        ),
    ]
