# Generated by Django 5.0.1 on 2024-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0051_remove_add_uttarpradesh_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_uttarpradesh',
            name='Weight',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
