# Generated by Django 5.0.1 on 2024-07-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0054_add_maharashtra_grand_tottal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_maharashtra',
            name='Weight',
        ),
    ]
