# Generated by Django 5.0.1 on 2024-07-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0055_remove_add_maharashtra_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_maharashtra',
            name='recipt_no',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
