# Generated by Django 5.0.1 on 2024-07-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0057_add_gujrat_total_amt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gujrat',
            name='Weight',
        ),
    ]
