# Generated by Django 5.0.1 on 2024-07-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0058_remove_add_gujrat_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_jharkhand',
            name='checkpost',
        ),
    ]
