# Generated by Django 5.0.1 on 2024-07-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0059_remove_add_jharkhand_checkpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_jharkhand',
            name='Weight',
        ),
    ]
