# Generated by Django 5.0.1 on 2024-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0060_remove_add_jharkhand_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jharkhand',
            name='recipt_no',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
