# Generated by Django 5.0.1 on 2024-07-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0061_add_jharkhand_recipt_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_uttrakhand',
            name='Pay_Tax',
        ),
        migrations.RemoveField(
            model_name='add_uttrakhand',
            name='Weight',
        ),
    ]
