# Generated by Django 5.0.1 on 2024-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0062_remove_add_uttrakhand_pay_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_uttrakhand',
            name='recipt_no',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
