# Generated by Django 5.0.1 on 2024-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0063_add_uttrakhand_recipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_uttrakhand',
            name='grand_tottal',
            field=models.IntegerField(default=0),
        ),
    ]
