# Generated by Django 5.0.1 on 2024-07-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0064_add_uttrakhand_grand_tottal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_himachal',
            name='Weight',
        ),
    ]
