# Generated by Django 5.0.1 on 2024-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhaanmain', '0066_remove_add_himachal_txt_no_of_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_bihar',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='add_karnataka',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='add_rajasthan',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='add_uttarpradesh',
            name='Weight',
        ),
    ]
